<?php

namespace App\Support;

use App\Models\JenisRefill;
use App\Models\Pelanggan;
use App\Models\Pesanan;
use App\Models\UnitApar;
use Carbon\Carbon;
use Carbon\CarbonInterface;
use Illuminate\Support\Collection;

class RegisteredRefillUnitSupport
{
    public const PREFILL_GROUP_KEY = '__prefilled__';
    public const REFILL_WARNING_DAYS = 7;

    public static function statusMeta(UnitApar $unitApar, int $warningDays = self::REFILL_WARNING_DAYS): array
    {
        return static::statusMetaFromExpiry($unitApar->tgl_expired, $warningDays);
    }

    public static function statusMetaFromExpiry(
        CarbonInterface|string|null $expiredAt,
        int $warningDays = self::REFILL_WARNING_DAYS
    ): array {
        $today = now()->startOfDay();
        $expiredDate = static::normalizeExpiryDate($expiredAt);
        $daysUntilExpiry = $expiredDate
            ? (int) $today->diffInDays($expiredDate, false)
            : null;
        $isExpired = ! is_null($daysUntilExpiry) && $daysUntilExpiry < 0;
        $isExpiringSoon = ! $isExpired && ! is_null($daysUntilExpiry) && $daysUntilExpiry <= $warningDays;
        $needsRefill = $isExpired || $isExpiringSoon;
        $statusKey = $isExpired ? 'expired' : ($isExpiringSoon ? 'hampir' : 'aman');

        return [
            'status_key' => $statusKey,
            'days_until_expiry' => $daysUntilExpiry,
            'is_expired' => $isExpired,
            'is_expiring_soon' => $isExpiringSoon,
            'needs_refill' => $needsRefill,
            'status_label' => match ($statusKey) {
                'expired' => 'Expired',
                'hampir' => 'Hampir Expired',
                default => 'Aman',
            },
            'expired_at_label' => static::formatDateLabel($expiredDate),
            'expired_at_short_label' => static::formatShortDateLabel($expiredDate),
            'remaining_label' => static::remainingLabel($daysUntilExpiry, $today, $expiredDate),
            'notice_text' => static::noticeText($statusKey, $daysUntilExpiry, $expiredDate),
        ];
    }

    public static function orderReferencesUnit(Pesanan $pesanan, UnitApar $unitApar): bool
    {
        $resolvedUnits = static::resolveRegisteredUnitsForOrder($pesanan);

        return $resolvedUnits->contains(fn (UnitApar $resolvedUnit) => (int) $resolvedUnit->id === (int) $unitApar->id);
    }

    public static function activeRefillLocks(Pelanggan $pelanggan): array
    {
        $orders = Pesanan::query()
            ->with(['service.unitApar.produk.jenisApar', 'pelanggan'])
            ->where('pelanggan_id', $pelanggan->id)
            ->where('tipe', 'service')
            ->where('service_jenis_layanan', 'refill')
            ->whereNotIn('status', [
                Pesanan::STATUS_SELESAI,
                Pesanan::STATUS_SELESAI_FINAL,
                Pesanan::STATUS_DITOLAK,
            ])
            ->latest('id')
            ->get();

        $locks = [];

        foreach ($orders as $order) {
            foreach (static::resolveRegisteredUnitsForOrder($order) as $unitApar) {
                $locks[(int) $unitApar->id] = [
                    'pesanan_id' => (int) $order->id,
                    'status_label' => $order->publicStatusLabel(),
                    'message' => 'Unit ini sedang dalam proses refill.',
                ];
            }
        }

        return $locks;
    }

    public static function resolveRegisteredUnitsForOrder(Pesanan $pesanan): Collection
    {
        if ($pesanan->tipe !== 'service') {
            return collect();
        }

        $pesanan->loadMissing(['service.unitApar.produk.jenisApar']);

        $units = collect();
        $serviceUnit = $pesanan->service?->unitApar;

        if ($serviceUnit && ! $serviceUnit->isHiddenFromListings() && ! static::isAutoGeneratedUnit($serviceUnit)) {
            $units->push($serviceUnit);
        }

        $display = ServiceUnitDisplay::forPesanan($pesanan);
        $entries = collect($display['entries'] ?? []);
        $codes = $entries
            ->pluck('code')
            ->map(fn ($code) => trim((string) $code))
            ->filter()
            ->values();

        if ($codes->isNotEmpty() && $pesanan->pelanggan_id) {
            $matchedUnits = UnitApar::query()
                ->visible()
                ->with('produk.jenisApar')
                ->where('pelanggan_id', $pesanan->pelanggan_id)
                ->whereIn('no_seri', $codes->all())
                ->get()
                ->keyBy(fn (UnitApar $unitApar) => trim((string) $unitApar->no_seri));

            foreach ($codes as $code) {
                $matchedUnit = $matchedUnits->get($code);

                if ($matchedUnit) {
                    $units->push($matchedUnit);
                }
            }
        }

        return $units
            ->filter(fn ($unitApar) => $unitApar instanceof UnitApar)
            ->unique(fn (UnitApar $unitApar) => (int) $unitApar->id)
            ->values();
    }

    public static function parseRefillUnitDetails(string $note): array
    {
        $details = [];
        $lines = preg_split('/\r\n|\r|\n/', $note) ?: [];

        foreach ($lines as $line) {
            $line = trim((string) $line);
            if ($line === '') {
                continue;
            }

            if (preg_match('/^\d+\.\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(\d+)\s*unit\s*-\s*Rp\s*([\d\.]+)/u', $line, $matches)) {
                $refillLabel = trim((string) ($matches[1] ?? ''));
                $ukuran = trim((string) ($matches[2] ?? ''));
                $qty = max(1, (int) ($matches[3] ?? 1));
                $ukuranKg = 0.0;

                if (preg_match('/(\d+(?:[.,]\d+)?)/', $ukuran, $sizeMatch)) {
                    $ukuranKg = (float) str_replace(',', '.', (string) ($sizeMatch[1] ?? '0'));
                }

                $details[] = [
                    'code' => null,
                    'label' => trim($refillLabel . ' | ' . $ukuran),
                    'refill_label' => $refillLabel,
                    'usage_kg' => round($ukuranKg * $qty, 2),
                    'usage_unit' => 'Kg',
                    'amount' => (float) str_replace('.', '', (string) ($matches[4] ?? '0')),
                ];

                continue;
            }

            if (! preg_match('/^\d+\.\s*(.+?)\s+-\s+Masa berlaku:\s+(.+?)\s+-\s+Refill:\s+(.+?)\s+-\s+Kebutuhan:\s+([\d.,]+)\s*([A-Za-z]+)(?:\s+-\s+Rp([\d\.]+))?$/u', $line, $matches)) {
                continue;
            }

            $payload = trim((string) ($matches[1] ?? ''));
            $parts = collect(explode(' - ', $payload))
                ->map(fn ($part) => trim((string) $part))
                ->filter()
                ->values();

            $details[] = [
                'code' => $parts->get(0),
                'label' => $parts->get(1) ?: $payload,
                'refill_label' => trim((string) ($matches[3] ?? '')),
                'usage_kg' => (float) str_replace(',', '.', (string) ($matches[4] ?? '0')),
                'usage_unit' => trim((string) ($matches[5] ?? 'Kg')),
                'amount' => isset($matches[6]) ? (float) str_replace('.', '', (string) $matches[6]) : 0.0,
            ];
        }

        return $details;
    }

    public static function matchJenisRefillByLabel(Collection $jenisRefills, string $label): ?JenisRefill
    {
        $source = static::normalizeRefillText($label);
        if ($source === '') {
            return null;
        }

        return $jenisRefills->first(function (JenisRefill $jenisRefill) use ($source) {
            $nama = static::normalizeRefillText((string) $jenisRefill->nama);
            $namaLabel = static::normalizeRefillText((string) $jenisRefill->nama_label);

            return ($nama !== '' && ($source === $nama || str_contains($source, $nama) || str_contains($nama, $source)))
                || ($namaLabel !== '' && ($source === $namaLabel || str_contains($source, $namaLabel) || str_contains($namaLabel, $source)));
        });
    }

    private static function normalizeRefillText(?string $value): string
    {
        $text = mb_strtolower(trim((string) $value));
        $text = preg_replace('/[^a-z0-9]+/u', ' ', $text) ?? $text;
        $text = preg_replace('/\s+/', ' ', $text) ?? $text;

        return trim($text);
    }

    private static function isAutoGeneratedUnit(?UnitApar $unitApar): bool
    {
        if (! $unitApar) {
            return false;
        }

        $note = mb_strtolower(trim((string) ($unitApar->catatan_unit ?? '')));
        $serial = strtoupper(trim((string) ($unitApar->no_seri ?? '')));

        return str_contains($note, 'unit dibuat otomatis dari')
            || str_starts_with($serial, 'AUTO-');
    }

    private static function normalizeExpiryDate(CarbonInterface|string|null $expiredAt): ?CarbonInterface
    {
        if ($expiredAt instanceof CarbonInterface) {
            return $expiredAt->copy()->startOfDay();
        }

        $raw = trim((string) $expiredAt);
        if ($raw === '') {
            return null;
        }

        try {
            return Carbon::parse($raw)->startOfDay();
        } catch (\Throwable) {
            return null;
        }
    }

    private static function remainingLabel(
        ?int $daysUntilExpiry,
        CarbonInterface $today,
        ?CarbonInterface $expiredDate
    ): string {
        if (is_null($daysUntilExpiry) || ! $expiredDate) {
            return '-';
        }

        if ($daysUntilExpiry < 0) {
            return 'Expired';
        }

        if ($daysUntilExpiry === 0) {
            return 'Hari ini';
        }

        $monthsUntilExpiry = (int) floor($today->diffInMonths($expiredDate));
        if ($monthsUntilExpiry >= 1) {
            $anchorDate = $today->copy()->addMonths($monthsUntilExpiry);
            $remainingDays = max(0, (int) $anchorDate->diffInDays($expiredDate, false));

            if ($remainingDays > 0 && $monthsUntilExpiry < 6) {
                return $monthsUntilExpiry . ' bulan ' . $remainingDays . ' hari';
            }

            return $monthsUntilExpiry . ' bulan';
        }

        return $daysUntilExpiry . ' hari';
    }

    private static function noticeText(string $statusKey, ?int $daysUntilExpiry, ?CarbonInterface $expiredDate): string
    {
        if (! $expiredDate) {
            return 'Masa berlaku unit belum tersedia.';
        }

        $expiredLabel = static::formatDateLabel($expiredDate);

        return match ($statusKey) {
            'expired' => 'Unit sudah melewati masa berlaku pada ' . $expiredLabel . '.',
            'hampir' => $daysUntilExpiry === 0
                ? 'Masa berlaku unit berakhir hari ini, ' . $expiredLabel . '.'
                : 'Masa berlaku unit tinggal ' . $daysUntilExpiry . ' hari, sampai ' . $expiredLabel . '.',
            default => 'Masa berlaku unit masih aktif sampai ' . $expiredLabel . '.',
        };
    }

    private static function formatDateLabel(?CarbonInterface $date): string
    {
        return $date?->copy()->locale('id')->isoFormat('D MMMM YYYY') ?? '-';
    }

    private static function formatShortDateLabel(?CarbonInterface $date): string
    {
        return $date?->copy()->locale('id')->isoFormat('D MMM YYYY') ?? '-';
    }
}
