<?php

namespace App\Support;

use App\Models\JenisRefill;
use App\Models\Pelanggan;
use App\Models\Pesanan;
use App\Models\UnitApar;
use Illuminate\Support\Collection;

class RegisteredRefillUnitSupport
{
    public const PREFILL_GROUP_KEY = '__prefilled__';

    public static function statusMeta(UnitApar $unitApar, int $warningDays = 30): array
    {
        $daysUntilExpiry = $unitApar->tgl_expired
            ? (int) now()->startOfDay()->diffInDays($unitApar->tgl_expired->copy()->startOfDay(), false)
            : null;

        $isExpired = ! is_null($daysUntilExpiry) && $daysUntilExpiry < 0;
        $isExpiringSoon = ! $isExpired && ! is_null($daysUntilExpiry) && $daysUntilExpiry <= $warningDays;
        $needsRefill = $isExpired || $isExpiringSoon;

        return [
            'days_until_expiry' => $daysUntilExpiry,
            'is_expired' => $isExpired,
            'is_expiring_soon' => $isExpiringSoon,
            'needs_refill' => $needsRefill,
            'status_label' => $needsRefill ? 'Perlu Refill' : 'Aman',
        ];
    }

    public static function activeRefillLocks(Pelanggan $pelanggan): array
    {
        $orders = Pesanan::query()
            ->with(['service.unitApar.produk.jenisApar', 'pelanggan'])
            ->where('pelanggan_id', $pelanggan->id)
            ->where('tipe', 'service')
            ->where('service_jenis_layanan', 'refill')
            ->whereNotIn('status', [
                Pesanan::STATUS_SELESAI,
                Pesanan::STATUS_SELESAI_FINAL,
                Pesanan::STATUS_DITOLAK,
            ])
            ->latest('id')
            ->get();

        $locks = [];

        foreach ($orders as $order) {
            foreach (static::resolveRegisteredUnitsForOrder($order) as $unitApar) {
                $locks[(int) $unitApar->id] = [
                    'pesanan_id' => (int) $order->id,
                    'status_label' => $order->publicStatusLabel(),
                    'message' => 'Unit ini sedang dalam proses refill.',
                ];
            }
        }

        return $locks;
    }

    public static function resolveRegisteredUnitsForOrder(Pesanan $pesanan): Collection
    {
        if ($pesanan->tipe !== 'service') {
            return collect();
        }

        $pesanan->loadMissing(['service.unitApar.produk.jenisApar']);

        $units = collect();
        $serviceUnit = $pesanan->service?->unitApar;

        if ($serviceUnit && ! static::isAutoGeneratedUnit($serviceUnit)) {
            $units->push($serviceUnit);
        }

        $display = ServiceUnitDisplay::forPesanan($pesanan);
        $entries = collect($display['entries'] ?? []);
        $codes = $entries
            ->pluck('code')
            ->map(fn ($code) => trim((string) $code))
            ->filter()
            ->values();

        if ($codes->isNotEmpty() && $pesanan->pelanggan_id) {
            $matchedUnits = UnitApar::query()
                ->with('produk.jenisApar')
                ->where('pelanggan_id', $pesanan->pelanggan_id)
                ->whereIn('no_seri', $codes->all())
                ->get()
                ->keyBy(fn (UnitApar $unitApar) => trim((string) $unitApar->no_seri));

            foreach ($codes as $code) {
                $matchedUnit = $matchedUnits->get($code);

                if ($matchedUnit) {
                    $units->push($matchedUnit);
                }
            }
        }

        return $units
            ->filter(fn ($unitApar) => $unitApar instanceof UnitApar)
            ->unique(fn (UnitApar $unitApar) => (int) $unitApar->id)
            ->values();
    }

    public static function parseRefillUnitDetails(string $note): array
    {
        $details = [];
        $lines = preg_split('/\r\n|\r|\n/', $note) ?: [];

        foreach ($lines as $line) {
            $line = trim((string) $line);
            if ($line === '') {
                continue;
            }

            if (! preg_match('/^\d+\.\s*(.+?)\s+-\s+Masa berlaku:\s+(.+?)\s+-\s+Refill:\s+(.+?)\s+-\s+Kebutuhan:\s+([\d.,]+)\s*([A-Za-z]+)(?:\s+-\s+Rp([\d\.]+))?$/u', $line, $matches)) {
                continue;
            }

            $payload = trim((string) ($matches[1] ?? ''));
            $parts = collect(explode(' - ', $payload))
                ->map(fn ($part) => trim((string) $part))
                ->filter()
                ->values();

            $details[] = [
                'code' => $parts->get(0),
                'label' => $parts->get(1) ?: $payload,
                'refill_label' => trim((string) ($matches[3] ?? '')),
                'usage_kg' => (float) str_replace(',', '.', (string) ($matches[4] ?? '0')),
                'usage_unit' => trim((string) ($matches[5] ?? 'Kg')),
                'amount' => isset($matches[6]) ? (float) str_replace('.', '', (string) $matches[6]) : 0.0,
            ];
        }

        return $details;
    }

    public static function matchJenisRefillByLabel(Collection $jenisRefills, string $label): ?JenisRefill
    {
        $source = static::normalizeRefillText($label);
        if ($source === '') {
            return null;
        }

        return $jenisRefills->first(function (JenisRefill $jenisRefill) use ($source) {
            $nama = static::normalizeRefillText((string) $jenisRefill->nama);
            $namaLabel = static::normalizeRefillText((string) $jenisRefill->nama_label);

            return ($nama !== '' && ($source === $nama || str_contains($source, $nama) || str_contains($nama, $source)))
                || ($namaLabel !== '' && ($source === $namaLabel || str_contains($source, $namaLabel) || str_contains($namaLabel, $source)));
        });
    }

    private static function normalizeRefillText(?string $value): string
    {
        $text = mb_strtolower(trim((string) $value));
        $text = preg_replace('/[^a-z0-9]+/u', ' ', $text) ?? $text;
        $text = preg_replace('/\s+/', ' ', $text) ?? $text;

        return trim($text);
    }

    private static function isAutoGeneratedUnit(?UnitApar $unitApar): bool
    {
        if (! $unitApar) {
            return false;
        }

        $note = mb_strtolower(trim((string) ($unitApar->catatan_unit ?? '')));
        $serial = strtoupper(trim((string) ($unitApar->no_seri ?? '')));

        return str_contains($note, 'unit dibuat otomatis dari')
            || str_starts_with($serial, 'AUTO-');
    }
}
