<?php

namespace App\Support;

use App\Models\Pesanan;
use App\Models\Refill;
use App\Models\Service;
use App\Models\UnitApar;

class ServiceUnitDisplay
{
    public static function empty(): array
    {
        return [
            'is_registered' => false,
            'heading' => 'APAR Tidak Terdaftar',
            'entries' => [],
            'quantity' => 0,
            'quantity_label' => null,
            'detail_label' => null,
            'summary' => '-',
        ];
    }

    public static function forPesanan(Pesanan $pesanan): array
    {
        if ($pesanan->tipe !== 'service') {
            return static::empty();
        }

        $pesanan->loadMissing(['service.unitApar.produk.jenisApar', 'serviceJenisRefill']);

        $registeredEntries = static::registeredOrderEntries($pesanan);
        if ($registeredEntries !== []) {
            return static::payload(true, $registeredEntries, count($registeredEntries));
        }

        $manualLabel = static::manualOrderLabel($pesanan);

        return static::payload(
            false,
            $manualLabel !== '' ? [[
                'label' => $manualLabel,
                'code' => null,
            ]] : [],
            max(1, (int) ($pesanan->service_jumlah_unit ?? 1)),
            $manualLabel,
        );
    }

    public static function forService(Service $service): array
    {
        $service->loadMissing(['pesanan.service.unitApar.produk.jenisApar', 'pesanan.serviceJenisRefill', 'unitApar.produk.jenisApar']);

        if ($service->pesanan) {
            return static::forPesanan($service->pesanan);
        }

        if ($service->unitApar && ! static::isAutoGeneratedUnit($service->unitApar)) {
            return static::payload(true, [static::registeredUnitEntry($service->unitApar)], 1);
        }

        $manualLabel = static::formatManualAparLabel(
            $service->unitApar?->produk?->jenisApar?->nama ?: $service->unitApar?->bahan,
            $service->unitApar?->ukuran ?: $service->unitApar?->produk?->kapasitas,
        );

        return static::payload(
            false,
            $manualLabel !== '' ? [[
                'label' => $manualLabel,
                'code' => null,
            ]] : [],
            1,
            $manualLabel,
        );
    }

    public static function forRefill(Refill $refill): array
    {
        $refill->loadMissing(['service.pesanan.service.unitApar.produk.jenisApar', 'service.pesanan.serviceJenisRefill', 'unitApar.produk.jenisApar', 'jenisRefill']);

        if ($refill->service?->pesanan) {
            return static::forPesanan($refill->service->pesanan);
        }

        if ($refill->unitApar && ! static::isAutoGeneratedUnit($refill->unitApar)) {
            return static::payload(true, [static::registeredUnitEntry($refill->unitApar)], 1);
        }

        $manualLabel = static::formatManualAparLabel(
            $refill->jenisRefill?->nama_label ?: $refill->unitApar?->bahan,
            $refill->unitApar?->ukuran ?: $refill->unitApar?->produk?->kapasitas,
        );

        return static::payload(
            false,
            $manualLabel !== '' ? [[
                'label' => $manualLabel,
                'code' => null,
            ]] : [],
            1,
            $manualLabel,
        );
    }

    public static function forUnitApar(UnitApar $unitApar): array
    {
        $unitApar->loadMissing('produk.jenisApar');

        if (static::isAutoGeneratedUnit($unitApar)) {
            $manualLabel = static::formatManualAparLabel(
                $unitApar->produk?->jenisApar?->nama ?: $unitApar->bahan,
                $unitApar->ukuran ?: $unitApar->produk?->kapasitas,
            );

            return static::payload(false, $manualLabel !== '' ? [[
                'label' => $manualLabel,
                'code' => null,
            ]] : [], 1, $manualLabel);
        }

        return static::payload(true, [static::registeredUnitEntry($unitApar)], 1);
    }

    private static function payload(
        bool $isRegistered,
        array $entries,
        int $quantity = 0,
        ?string $detailLabel = null
    ): array
    {
        $entries = collect($entries)
            ->filter(fn ($entry) => filled($entry['label'] ?? null))
            ->map(function ($entry) {
                return [
                    'label' => trim((string) ($entry['label'] ?? '')),
                    'code' => filled(trim((string) ($entry['code'] ?? '')))
                        ? trim((string) $entry['code'])
                        : null,
                ];
            })
            ->unique(fn ($entry) => mb_strtolower(($entry['label'] ?? '') . '|' . ($entry['code'] ?? '')))
            ->values()
            ->all();

        $quantity = max($quantity, $isRegistered ? count($entries) : 0);
        $detailLabel = trim((string) ($detailLabel ?? ($entries[0]['label'] ?? '')));
        $quantityLabel = $quantity > 0 ? 'Jumlah Unit: ' . $quantity . ' unit' : null;

        return [
            'is_registered' => $isRegistered,
            'heading' => $isRegistered ? 'Unit APAR Terdaftar' : 'APAR Tidak Terdaftar',
            'entries' => $entries,
            'quantity' => $quantity,
            'quantity_label' => $quantityLabel,
            'detail_label' => $detailLabel !== '' ? $detailLabel : null,
            'summary' => $entries[0]['label'] ?? '-',
        ];
    }

    private static function registeredOrderEntries(Pesanan $pesanan): array
    {
        $unitApar = $pesanan->service?->unitApar;
        if ($unitApar && ! static::isAutoGeneratedUnit($unitApar)) {
            return [static::registeredUnitEntry($unitApar)];
        }

        if (! static::orderUsesRegisteredUnit($pesanan)) {
            return [];
        }

        return static::parseRegisteredEntriesFromNote((string) ($pesanan->service_keluhan ?? ''));
    }

    private static function orderUsesRegisteredUnit(Pesanan $pesanan): bool
    {
        $texts = [
            (string) ($pesanan->keterangan ?? ''),
            (string) ($pesanan->service_keluhan ?? ''),
        ];

        foreach ($texts as $text) {
            if (str_contains(mb_strtolower($text), 'status unit: apar terdaftar')) {
                return true;
            }
        }

        return false;
    }

    private static function parseRegisteredEntriesFromNote(string $note): array
    {
        $entries = [];
        $lines = preg_split('/\r\n|\r|\n/', $note) ?: [];

        foreach ($lines as $line) {
            $line = trim((string) $line);
            if ($line === '') {
                continue;
            }

            if (! preg_match('/^\d+\.\s*(.+?)(?:\s+-\s+Masa berlaku:|\s+-\s+Rp|\s+x\s+\d+\s+unit|$)/iu', $line, $matches)) {
                continue;
            }

            $payload = trim((string) ($matches[1] ?? ''));
            if ($payload === '') {
                continue;
            }

            $parts = collect(explode(' - ', $payload))
                ->map(fn ($part) => trim((string) $part))
                ->filter()
                ->values();

            $entries[] = [
                'label' => $parts->get(1) ?: $payload,
                'code' => $parts->get(0) ?: null,
            ];
        }

        return $entries;
    }

    private static function registeredUnitEntry(UnitApar $unitApar): array
    {
        $unitApar->loadMissing('produk.jenisApar');

        $label = trim((string) (
            $unitApar->produk?->nama
            ?: static::formatManualAparLabel(
                $unitApar->produk?->jenisApar?->nama ?: $unitApar->bahan,
                $unitApar->ukuran ?: $unitApar->produk?->kapasitas,
            )
        ));

        return [
            'label' => $label !== '' ? $label : 'APAR',
            'code' => filled(trim((string) $unitApar->no_seri)) ? trim((string) $unitApar->no_seri) : null,
        ];
    }

    private static function manualOrderLabel(Pesanan $pesanan): string
    {
        $ukuran = trim((string) ($pesanan->service_ukuran_apar ?? ''));
        $media = trim((string) ($pesanan->service_jenis_apar ?? ''));

        if ($pesanan->isRefillOrder()) {
            $refillLabel = trim((string) ($pesanan->serviceJenisRefill?->nama_label ?? ''));
            $normalizedMedia = mb_strtolower($media);
            $normalizedUkuran = mb_strtolower($ukuran);

            $mediaLooksLikeSizeOnly = $normalizedMedia === ''
                || $normalizedMedia === $normalizedUkuran
                || $normalizedMedia === 'apar ' . $normalizedUkuran;

            $mediaMissingRefillType = $refillLabel !== ''
                && $normalizedMedia !== ''
                && ! str_contains($normalizedMedia, mb_strtolower($refillLabel));

            if ($refillLabel !== '' && ($mediaLooksLikeSizeOnly || $mediaMissingRefillType)) {
                $media = $refillLabel;
            }
        }

        return static::formatManualAparLabel($media, $ukuran);
    }

    private static function formatManualAparLabel(?string $media, ?string $ukuran): string
    {
        $media = trim((string) $media);
        $ukuran = trim((string) $ukuran);

        if ($media === '' && $ukuran === '') {
            return '';
        }

        $base = $media;
        if ($base === '') {
            $base = 'APAR';
        } elseif (! str_starts_with(mb_strtolower($base), 'apar')) {
            $base = 'APAR ' . $base;
        }

        if ($ukuran !== '' && ! str_contains(mb_strtolower($base), mb_strtolower($ukuran))) {
            $base .= ' ' . $ukuran;
        }

        return trim((string) preg_replace('/\s+/', ' ', $base));
    }

    private static function isAutoGeneratedUnit(?UnitApar $unitApar): bool
    {
        if (! $unitApar) {
            return false;
        }

        $note = mb_strtolower(trim((string) ($unitApar->catatan_unit ?? '')));
        $serial = strtoupper(trim((string) ($unitApar->no_seri ?? '')));

        return str_contains($note, 'unit dibuat otomatis dari')
            || str_starts_with($serial, 'AUTO-');
    }
}
